[package]
name = "toml-bin"
version = "1.0.0"
authors = ["Xnuk Shuman <admin@xnu.kr>"]
edition = "2021"

[dependencies]
toml = "0.8.14"
serde_json = "1.0.117"

[[bin]]
name = "toml"
path = "main.rs"

[profile.release]
strip = true
lto = true
